---
  - name: restart postfix
    become: True
    service:
      name: postfix@-
      enabled: yes
      state: restarted

  - name: restart krbhelper
    become: True
    service:
      name: postfix-krbhelper.timer
      enabled: yes
      state: restarted

  - name: reload systemd-postfix
    become: True
    service:
      name: postfix@-
      enabled: yes
      state: restarted
      daemon_reload: yes

  - name: reload systemd-krbhelper
    become: True
    service:
      name: postfix-krbhelper.timer
      enabled: yes
      state: restarted
      daemon_reload: yes

  - name: newalias
    become: True
    command: newaliases

  - name: rebuild sender map
    become: True
    command: postmap /etc/postfix/sender_canonical_maps
    args:
      chdir: /etc/postfix
    notify:
      - restart postfix

  - name: rebuild header map
    become: True
    command: postmap /etc/postfix/header_check
    args:
      chdir: /etc/postfix
    notify:
      - restart postfix

  - name: rebuild sasl map
    become: True
    command: postmap /etc/postfix/sasl_passwd
    args:
      chdir: /etc/postfix
    notify:
      - restart postfix
